language: cpp

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libwww-perl
            - g++-5
      before_install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libwww-perl
            - clang-3.7
      before_install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-3.7 90
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: gcc
      env: COMPILER=g++
    - os: osx
      compiler: clang
      env: COMPILER=clang++
    - env: NAME="CPP-LINT"
      before_script: git fetch origin master:master
      script: scripts/run_lint.sh master HEAD

script:
  - ./build.sh $COMPILER -j4 && cd regression && make test
